### ISSUE TITLE
Duplicate txs queued in the same epoch show inconsistent execution result

### ISSUE THREAD

**Issue by gitferry** [babylonchain/babylon#314]
For example, two `WrappedCreateValidator` messages are submitted within the same epoch. The execution result will show that they are all executed successfully. But when it comes to the epoch ends, one of them might fail due to being out of gas. Maybe we should avoid duplicate txs within the same epoch? cc @vitsalis @SebastianElvis

**Comment by SebastianElvis** [comment]
Thanks for pointing this out.

My feeling is that we should not avoid duplicate txs, since it's not straightforward to define whether two txs are duplicated. For example, one can create two delegations/undelegations/redelegations in a single epoch. The two txs can be both valid and will be executed successfully. One exception, as you mentioned, is `WrappedCreateValidator`, since one has to specify a PK for the validator but two validators cannot share the same PK.

In addition, the duplication check has to be stateful, in the sense that whether a tx is duplicated depends on the txs in the existing ledger. Such stateful check cannot be performed in AnteHandler since stateful AnteHandler check leads to DoS vector. It is also not ideal to be added as a verification rule for the tx either, since these verification rules will be executed again when the epoch ends anyway.

Another thing is that, this question can be generalised to another one: whether we should perform stateful checks upon a staking-related tx. The checks include duplication checks, as well as something else e.g., whether the account is guaranteed to still have enough tokens when the epoch ends. The answer seems to be negative -- the account's state is unpredictable and manipulatable in the period between the tx is submitted and the epoch ends. For example, one can send a legitimate `WrappedCreateValidator`, then spend a lot of tokens, such that `WrappedCreateValidator` will fail at the end of this epoch. That's exactly why we need to perform these stateful checks again when an epoch ends. 

These points are noted from [ADR-039](https://github.com/cosmos/cosmos-sdk/blob/main/docs/architecture/adr-039-epoched-staking.md) and [our investigations](https://babylon-chain.atlassian.net/wiki/spaces/BABYLON/pages/12976155/Analysis+of+ADR-039+Epoched+Staking). The ADR-039 also suggests an alternative to implement token lockup upon staking-related txs. It looks a bit overkill at the moment, and we could not find any such practice in existing Cosmos zones when doing the investigation. Thus we decided to simply fail the msg if it becomes invalid at the end of an epoch.
